# Generated by Django 4.1.7 on 2023-02-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LFiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlVal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
            ],
        ),
    ]
